{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "netdata.fullname" . }}
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources:
      - "nodes"
      - "pods"
      - "services"
      - "endpoints"
      - "configmaps"
      - "secrets"
      - "events"
      - "componentstatuses"
      - "nodes/proxy"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups: [""]
    resources:
      - "namespaces"
      - "resourcequotas"
    verbs:
      - "get"
      - "list"
  - apiGroups: [""]
    resources:
      - "nodes/metrics"
      - "nodes/spec"
    verbs:
      - "get"
  - apiGroups: ["extensions"]
    resources:
      - "ingresses"
    verbs:
      - "get"
      - "list"
      - "watch"
  - nonResourceURLs: ["/version", "/healthz", "/metrics"]
    verbs:
      - "get"
  {{- end -}}
