{{- if and .Values.parent.enabled .Values.parent.database.persistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "netdata.name" . }}-parent-database
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: parent
spec:
  accessModes: [ "ReadWriteOnce" ]
  {{- if (ne "-" .Values.parent.database.storageclass) }}
  storageClassName: "{{ .Values.parent.database.storageclass }}"
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.parent.database.volumesize }}
{{- end }}

{{- if and .Values.parent.enabled .Values.parent.alarms.persistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "netdata.name" . }}-parent-alarms
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: parent
spec:
  accessModes: [ "ReadWriteOnce" ]
  {{- if (ne "-" .Values.parent.alarms.storageclass) }}
  storageClassName: "{{ .Values.parent.alarms.storageclass }}"
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.parent.alarms.volumesize }}
{{- end }}

{{- if and .Values.k8sState.enabled .Values.k8sState.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "netdata.name" . }}-k8s-state-varlib
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: k8sState
spec:
  accessModes: [ "ReadWriteOnce" ]
  {{- if (ne "-" .Values.k8sState.persistence.storageclass) }}
  storageClassName: "{{ .Values.k8sState.persistence.storageclass }}"
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.k8sState.persistence.volumesize }}
{{- end }}
