{{- if and .Values.serviceAccount.create (include "netdata.restarter.enabled" .) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "netdata.fullname" . }}-restarter
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "netdata.fullname" . }}-restarter
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}-restarter
    namespace: {{ .Release.Namespace }}
{{- end -}}
