{{- $secretParent := include "netdata.parent.configs.secret" . }}
{{- if and .Values.parent.enabled $secretParent }}
---
apiVersion: v1
kind: Secret
metadata:
  name: netdata-conf-parent
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ $secretParent | indent 2 }}
{{- end }}

{{- $secretChild := include "netdata.child.configs.secret" . }}
{{- if and .Values.child.enabled $secretChild}}
---
apiVersion: v1
kind: Secret
metadata:
  name: netdata-conf-child
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ $secretChild | indent 2 }}
{{- end }}

{{- $secretk8sState := include "netdata.k8sState.configs.secret" . }}
{{- if and .Values.k8sState.enabled $secretk8sState }}
---
apiVersion: v1
kind: Secret
metadata:
  name: netdata-conf-k8s-state
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ $secretk8sState | indent 2 }}
{{- end }}
