{{- if .Values.serviceAccount.create -}}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.serviceAccount.name }}
{{- end -}}

{{- if and .Values.serviceAccount.create (include "netdata.restarter.enabled" .) }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.serviceAccount.name }}-restarter
{{- end -}}
