apiVersion: v1
name: netdata
home: https://github.com/netdata/netdata
version: 1.1.8
appVersion: v1.18.1
description: Real-time performance monitoring, done right! https://my-netdata.io/
maintainers:
  - name: Chris Akritidis
    email: chris@netdata.cloud
  - name: Vladimir Ryumin
    email: vryumin@gmail.com
  - name: Karuppiah Natarajan
    email: karuppiah7890@gmail.com
  - name: Oleksii Kravchenko
    email: kamikaze.ua@gmail.com
