{{- $secretOtel := include "netdata.netdataOpentelemetry.configs.secret" . }}
{{- if and .Values.netdataOpentelemetry.enabled $secretOtel }}
---
apiVersion: v1
kind: Secret
metadata:
  name: netdata-conf-otel
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{ $secretOtel | indent 2 }}
{{- end }}
