{{- if .Values.child.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "netdata.name" . }}-child
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: child
spec:
  {{- with .Values.child.updateStrategy }}
  updateStrategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "netdata.name" . }}
      release: {{ .Release.Name }}
      role: child
  template:
    metadata:
      annotations:
      {{- if .Values.child.podAnnotationAppArmor.enabled }}
        container.apparmor.security.beta.kubernetes.io/{{ .Chart.Name }}: unconfined
      {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
{{- with .Values.child.podAnnotations }}
{{ toYaml . | trim | indent 8 }}
{{- end }}
      labels:
        app: {{ template "netdata.name" . }}
        release: {{ .Release.Name }}
        role: child
{{- with .Values.child.podLabels }}
{{ toYaml . | trim | indent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      restartPolicy: Always
      hostPID: true
      hostIPC: true
      hostNetwork: true
      {{- if .Values.child.priorityClassName }}
      priorityClassName: "{{ .Values.child.priorityClassName }}"
      {{- end }}
      initContainers:
      {{- if .Values.sysctlImage.enabled }}
        - name: init-sysctl
          image: "{{ .Values.sysctlImage.repository }}:{{ .Values.sysctlImage.tag }}"
          command:
{{ toYaml .Values.sysctlImage.command | indent 12 }}
          securityContext:
            runAsNonRoot: false
            privileged: true
            runAsUser: 0
          resources:
{{ toYaml .Values.sysctlImage.resources | indent 12 }}
      {{- end }}
        {{- if .Values.child.persistUniqueID }}
        - name: init-nodeuid
          image: netdata/wget
          volumeMounts:
            - name: nodeuid
              mountPath: "/nodeuid"
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - "/bin/sh"
          args:
            - "-c"
            - '
            TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token);
            URL="https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/api/v1/nodes/${MY_NODE_NAME}";
            HEADER="Authorization: Bearer ${TOKEN}";

            DATA=$(wget -q -T 5 --no-check-certificate --header "${HEADER}" -O - "${URL}");
            [ -z "${DATA}" ] && exit 1;

            UID=$(echo "${DATA}" | grep -m 1 uid | grep -o ":.*" | tr -d ": \",");
            [ -z "${UID}" ] && exit 1;

            echo -n "${UID}" > /nodeuid/netdata.public.unique.id;
            '
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.sd.child.enabled }}
            - name: NETDATA_PLUGINS_GOD_WATCH_PATH
              value: "/etc/netdata/go.d/sd/go.d.yml"
            {{- end }}
            {{- range $key, $value := .Values.child.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","killall netdata; while killall -0 netdata; do sleep 1; done"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/info
              port: http
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/info
              port: http
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: proc
              readOnly: true
              mountPath: /host/proc
            - name: run
              mountPath: /var/run/docker.sock
            - name: sys
              mountPath: /host/sys
            {{- range $name, $config := .Values.child.configs }}
            {{- if $config.enabled }}
            - name: config
              mountPath: {{ $config.path }}
              subPath: {{ $name }}
            {{- end }}
            {{- end }}
            {{- if .Values.child.persistUniqueID }}
            - name: nodeuid
              mountPath: "/var/lib/netdata/registry/"
            {{- end }}
            {{- if .Values.sd.child.enabled }}
            - name: sd-shared
              mountPath: "/etc/netdata/go.d/sd/"
            {{- end }}
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
                - SYS_ADMIN
          resources:
{{ toYaml .Values.child.resources | indent 12 }}
        {{- if .Values.sd.child.enabled }}
        - name: sd
          image: "{{ .Values.sd.repository }}:{{ .Values.sd.tag }}"
          imagePullPolicy: {{ .Values.sd.pullPolicy }}
          volumeMounts:
            - name: sd-shared
              mountPath: "/export/"
          resources:
          {{- toYaml .Values.sd.child.resources | nindent 12 }}
          env:
            - name: NETDATA_SD_CONFIG_MAP
              value: "{{ .Values.sd.child.configmap.name }}:{{ .Values.sd.child.configmap.key }}"
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        {{- end }}
    {{- with .Values.child.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.child.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.child.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: run
          hostPath:
            path: /var/run/docker.sock
        - name: sys
          hostPath:
            path: /sys
        - name: config
          configMap:
            name: netdata-conf-child
        {{- if .Values.child.persistUniqueID }}
        - name: nodeuid
          emptyDir: {}
        {{- end }}
        {{- if .Values.sd.child.enabled }}
        - name: sd-shared
          emptyDir: {}
        {{- end }}
      dnsPolicy: ClusterFirstWithHostNet
{{- end }}
